title: <p align="center"> Sunny M Sharma </p>
logo: /assets/img/Sunny-Sharma.JPG

description:
  <p align="center">
  <a href="https://in.linkedin.com/in/sunnyms">LinkedIn</a> |
  <a href="https://github.com/sunnyms">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
